# Generated by Django 3.0.6 on 2020-11-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanev', models.CharField(max_length=100)),
                ('jelszo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tetel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Valasztott',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanuloid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosztapp.Tanulo')),
                ('tetelid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosztapp.Tetel')),
            ],
        ),
    ]
